# ~/codes/todo-laravel/docker-compose.yaml

version: '3.8'

services:
  # Serviço da Aplicação (PHP-FPM)
  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - caddy_network

  # Serviço do Web Server (Nginx)
  todo_nginx:
    image: nginx:alpine
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - "8000:80" # Porta para acesso direto, opcional
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo_app
    networks:
      - caddy_network

  # Serviço do Banco de Dados (MySQL)
  todo_db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - todo_db_data:/var/lib/mysql
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true

volumes:
  todo_db_data:
